### ISSUE TITLE
Checking column types

### ISSUE THREAD

**Issue by dcjones** [UWSEDS/homework-2-python-functions-and-modules-Prattbuw#1]
This code checks that columns in the dataframe all have the same dtype, but it should check that values within each column have the same python type. The python type is obtained with `type(x)` and can be distinct from the column dtype.

```python
    for type in col_types:
        ...
```

**Comment by Prattbuw** [comment]
Hi Daniel, like I said in my HW3 comment, I did not get notified that an issue was raised with this homework. I know it is past a week since the issue was raised, but I still adjusted my homework to fix this issue. The new version homework that fixes the issue above is called, "create_dataframeV2.py". I hope it is still considered for a regrade. I'm sorry for the inconvenience this may cause. It was unclear to me how we would be receiving feedback on our homework. Three out of the four people in my project group didn't receive notifications about their homework either. I'm guessing this may be a general issue and should be addressed clearly in class.

**Comment by dcjones** [comment]
I'll let it slide, but "The instructors will respond to the homework as a github issue." is in the syllabus.

New test looks good.

7/7 points
